openapi: 3.0.1
info:
  title: Comision API
  description: API para gestionar las comisiones de empleados.
  version: "1.0.0"

paths:
  /api/comision:
    post:
      summary: Calcular comisiones para empleados.
      description: Endpoint para calcular la comisión en base a la venta realizada por un empleado.
      tags:
        - Comisiones
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestComision'
      responses:
        '200':
          description: Datos de la comisión calculada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseComision'
        '400':
          description: Error en la solicitud.
        '500':
          description: Error interno del servidor.

components:
  schemas:
    RequestComision:
      type: object
      properties:
        empleadoId:
          type: integer
          description: ID del empleado.
          example: 1234
        ventasTotales:
          type: number
          description: Monto total de ventas realizadas por el empleado.
          example: 1500.50
        porcentajeComision:
          type: number
          description: Porcentaje de comisión a aplicar sobre las ventas.
          example: 10.5

    ResponseComision:
      type: object
      properties:
        empleadoId:
          type: integer
          description: ID del empleado.
          example: 1234
        comisionGenerada:
          type: number
          description: Monto de comisión generada.
          example: 157.55
        totalVentas:
          type: number
          description: Total de ventas realizadas por el empleado.
          example: 1500.50
        porcentajeComision:
          type: number
          description: Porcentaje aplicado para calcular la comisión.
          example: 10.5
